### ISSUE TITLE
FR: Allow filtering out

### ISSUE THREAD

**Issue by brimwats** [cogscides/obsidian-keyboard-analyzer#2]
I'd like to see my Crtl + Alt commands but not the ones with shift. It would be nice to exclude those, or just include the ctrl ones for example

**Comment by cogscides** [comment]
@brimwats you mean something like strict mode to filter and display only hotkeys with exact type and number of modifiers, right?

So when you on strict mode, clicking by Ctrl should display only hotkeys with one Ctrl modifiers?

**Comment by brimwats** [comment]
you've got it!

**Comment by cogscides** [comment]
Added in [0.1.2](https://github.com/cogscides/obsidian-keyboard-analyzer/releases/tag/0.1.2)
