### ISSUE TITLE
Keyboard analyzer no longer opens

### ISSUE THREAD

**Issue by Randy-Astle** [cogscides/obsidian-keyboard-analyzer#8]
I installed Keyboard Analyzer in two vaults. 

After installation, clicking on the keyboard icon in the status bar displayed the Keyboard Analyzer. However, when I tried to display it in a new pane (CTRL + click), it did not display. More importantly, it no longer displays when I just click on the keyboard icon - even after closing and reopening Obsidian.

**Comment by cogscides** [comment]
@Randy-Astle try to check the sidebars. It's possible that plugin opened in the one of them.

**Comment by Randy-Astle** [comment]
I checked.
It didn't open in either sidebar.

**Comment by Randy-Astle** [comment]
Worked out what the problem was.

When I use CTRL + CLICK, it opens in a new tab but the tab doesn't get the focus.

I normally have multiple tabs open and I just didn't see it and got confused.

Thanks for your quick response.
